# ======================
# 共通設定
# ======================
system:
  encoding: utf-8
  timezone: Asia/Tokyo
  toAddress: "masahiro.sunai@persol.co.jp"
  target_month: 2026-04 # YYYY-MM 形式で指定。またはautoで自動判定。

# ======================
# Confluence
# ======================
confluence:
  dndev:
    url: https://aip01.dndev.net/wiki
    download_page_id: 344026675
    upload_page_id: 345088055
    cert_dir: C:/work/sunai/_work/MSE/JIRA_証明書/_latest/convert_certificate_keys
  geniie:
    url: https://wiki.geniie.net
    download_page_id: 4166906011
    upload_page_id: 4166906031
    # geniie 側は証明書不要

# ======================
# File / Path
# ======================
paths:
  workload_download_dir: //prd.local/share02/DS/D3/一時使用/21_DS2室/01_提出物/02_工数表/{YYYY}_{MM}
  workload_aggregate_file: //prd.local/share02/DS/D3/一時使用/21_DS2室/01_提出物/02_工数表/_管理/工数集計_{YY}{MM}.xlsm
  web_attendance_file: //prd.local/share02/DS/D3/一時使用/21_DS2室/01_提出物/02_工数表/_管理/Web勤怠整合性チェックツール/動作確認用 インプットファイル/Web勤怠_{YY}{MM}.csv
  member_file: //prd.local/share02/DS/D3/一時使用/21_DS2室/01_提出物/02_工数表/_管理/Web勤怠整合性チェックツール/動作確認用 インプットファイル/MemberNameList_v2_{YY}{MM}.csv
  work_map_file: //prd.local/share02/DS/D3/一時使用/21_DS2室/01_提出物/02_工数表/_管理/Web勤怠整合性チェックツール/動作確認用 インプットファイル/ワーク対応_{YY}{MM}.csv

# ======================
# Apps (Web勤怠)
# ======================
apps:
  base_url: https://appsfs-6454.my.salesforce.com
  filter_id: 00OfB00000fuq4L
  csv_suffix: "?csvsetup=1"

# ======================
# Rocket.Chat
# ======================
rocketchat:
  url: https://rc.dnjpchat.net
  room: pslmse6-jie1-nrd-chu1-tui4-qin2 #psl_MSE6階+NRD出退勤

# ======================
# Excel
# ======================
excel:
  macros:
    - "工数管理表読み込み"
    - "工数表_読み込み.工数管理表読み込み"
